name: Cargo Deny
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6 # v1.30.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ github.token }}
          tool: cargo-deny
      - uses: taiki-e/install-action@4684b8405694ae9dd42c9f39ba901a70ae83f4a3 # v2
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          tool: cargo-deny
      - name: Check advisories and licenses
        run: cargo deny check advisories licenses
